/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JOptionPane;


public class KonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhu
     */
    public KonversiSuhu() {
        initComponents();
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char input = evt.getKeyChar();
                if (!Character.isDigit(input) && input != '.') {
                    evt.consume();
                }
            }
        });

        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
    @Override
    public void itemStateChanged(java.awt.event.ItemEvent evt) {
        if (jRadioButton1.isSelected()) {
            konversiOtomatis();
        }
    }
});

        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (jRadioButton2.isSelected()) {
                    konversiOtomatis();
                }
            }
        });

        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (jRadioButton3.isSelected()) {
                    konversiOtomatis();
                }
            }
        });

        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (jRadioButton4.isSelected()) {
                    konversiOtomatis();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Konversi Suhu");

        jLabel1.setText("Masukkan Nilai Suhu : ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Pilih Opsi : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Opsi Skala Suhu Konversi ", "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));

        jLabel3.setText("Hasil");

        jLabel4.setText("Muhammad Subhan");

        jLabel5.setText("2210010215");

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel6.setText("PROGRAM APLIKASI KONVERSI SUHU");

        jRadioButton1.setText("Celcius");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Fahrenheit");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Kelvin");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Reamur");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Konversi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, 0, 233, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(jLabel3)
                                            .addGap(28, 28, 28))
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                    .addComponent(jRadioButton2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton4))))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String input = jTextField1.getText().trim(); // Menghapus spasi di awal dan akhir

        // Periksa apakah input kosong
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan nilai suhu yang valid.");
            return; // Keluar dari metode jika input kosong
        }

        double suhu;
        try {
            suhu = Double.parseDouble(input);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Masukkan nilai suhu yang valid.");
            return; // Keluar dari metode jika input tidak dapat dikonversi
        }

        String skalaAwal = (String) jComboBox1.getSelectedItem();
        String skalaTujuan = "";

        // Tentukan skala tujuan dari JRadioButton yang dipilih
        if (jRadioButton1.isSelected()) {
            skalaTujuan = "Celcius";
        } else if (jRadioButton2.isSelected()) {
            skalaTujuan = "Fahrenheit";
        } else if (jRadioButton3.isSelected()) {
            skalaTujuan = "Kelvin";
        } else if (jRadioButton4.isSelected()) {
            skalaTujuan = "Reamur";
        }

        // Jika skala awal dan skala tujuan tidak dipilih, gunakan default konversi dari Celcius ke Fahrenheit
        if (skalaAwal.equals("Skala Suhu") && skalaTujuan.isEmpty()) {
            skalaAwal = "Celcius";
            skalaTujuan = "Fahrenheit";
        } else if (skalaAwal.equals("Skala Suhu") || skalaTujuan.isEmpty()) {
            // Jika salah satu skala tidak dipilih, tampilkan pesan kesalahan
            JOptionPane.showMessageDialog(null, "Pilih skala suhu awal dan tujuan yang benar.");
            return; // Keluar dari metode jika skala tidak valid
        }

        double hasil = konversiSuhu(suhu, skalaAwal, skalaTujuan);
        jLabel3.setText("Hasil: " + hasil);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        double suhu = Double.parseDouble(jTextField1.getText());
        String skalaAwal = (String) jComboBox1.getSelectedItem();
        String skalaTujuan = "";

        // Tentukan skala tujuan dari JRadioButton yang dipilih
        if (jRadioButton1.isSelected()) {
            skalaTujuan = "Celcius";
        } else if (jRadioButton2.isSelected()) {
            skalaTujuan = "Fahrenheit";
        } else if (jRadioButton3.isSelected()) {
            skalaTujuan = "Kelvin";
        } else if (jRadioButton4.isSelected()) {
            skalaTujuan = "Reamur";
        }

        double hasil = 0;

        // Proses konversi berdasarkan pilihan skala
        if (!skalaAwal.equals("Skala Suhu") && !skalaTujuan.isEmpty()) {
            hasil = konversiSuhu(suhu, skalaAwal, skalaTujuan);
            jLabel3.setText("Hasil: " + hasil);
        } else {
            JOptionPane.showMessageDialog(null, "Pilih skala suhu awal dan tujuan yang benar.");
        }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private double konversiSuhu(double suhu, String skalaAwal, String skalaTujuan) {
       double hasil = 0;

    // Logika konversi suhu
    if (skalaAwal.equals("Celcius")) {
        if (skalaTujuan.equals("Fahrenheit")) {
            hasil = (suhu * 9 / 5) + 32;
        } else if (skalaTujuan.equals("Kelvin")) {
            hasil = suhu + 273.15;
        } else if (skalaTujuan.equals("Reamur")) {
            hasil = suhu * 4 / 5;
        } else {
            hasil = suhu; // jika skala tujuan sama
        }
    } else if (skalaAwal.equals("Fahrenheit")) {
        if (skalaTujuan.equals("Celcius")) {
            hasil = (suhu - 32) * 5 / 9;
        } else if (skalaTujuan.equals("Kelvin")) {
            hasil = (suhu - 32) * 5 / 9 + 273.15;
        } else if (skalaTujuan.equals("Reamur")) {
            hasil = (suhu - 32) * 4 / 9;
        } else {
            hasil = suhu; // jika skala tujuan sama
        }
    } else if (skalaAwal.equals("Kelvin")) {
        if (skalaTujuan.equals("Celcius")) {
            hasil = suhu - 273.15;
        } else if (skalaTujuan.equals("Fahrenheit")) {
            hasil = (suhu - 273.15) * 9 / 5 + 32;
        } else if (skalaTujuan.equals("Reamur")) {
            hasil = (suhu - 273.15) * 4 / 5;
        } else {
            hasil = suhu; // jika skala tujuan sama
        }
    } else if (skalaAwal.equals("Reamur")) {
        if (skalaTujuan.equals("Celcius")) {
            hasil = suhu * 5 / 4;
        } else if (skalaTujuan.equals("Fahrenheit")) {
            hasil = (suhu * 9 / 4) + 32;
        } else if (skalaTujuan.equals("Kelvin")) {
            hasil = (suhu * 5 / 4) + 273.15;
        } else {
            hasil = suhu; // jika skala tujuan sama
        }
    }

    return hasil;
}

    private void konversiOtomatis() {
    String input = jTextField1.getText().trim();

    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Masukkan nilai suhu yang valid.");
        return;
    }

    double suhu;
    try {
        suhu = Double.parseDouble(input);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Masukkan nilai suhu yang valid.");
        return;
    }

    String skalaAwal = (String) jComboBox1.getSelectedItem();
    String skalaTujuan = "";

    // Tentukan skala tujuan dari JRadioButton yang dipilih
    if (jRadioButton1.isSelected()) {
        skalaTujuan = "Celcius";
    } else if (jRadioButton2.isSelected()) {
        skalaTujuan = "Fahrenheit";
    } else if (jRadioButton3.isSelected()) {
        skalaTujuan = "Kelvin";
    } else if (jRadioButton4.isSelected()) {
        skalaTujuan = "Reamur";
    }

    if (skalaAwal.equals("Skala Suhu") || skalaTujuan.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Pilih skala suhu awal dan tujuan yang benar.");
        return;
    }

    double hasil = konversiSuhu(suhu, skalaAwal, skalaTujuan);
    jLabel3.setText("Hasil: " + hasil);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
